# Generated by Django 4.1.4 on 2022-12-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpiredPayments',
            new_name='ExpiredPayment',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
